version: '3'
services:
  web:
    image: sarahbatagioti/web-app
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: sarahbatagioti/db
    environment:
      MYSQL_DATABASE: MBViagens
      MYSQL_ROOT_PASSWORD: fatec
    ports:
      - "3306:3306"
