version: '3'
services:
  web:
    image: seu-usuario-dockerhub/web-app
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: seu-usuario-dockerhub/db
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
