version: '1.0'
services:
  app:
    image: app:5.0
    links:
      - 'db'
    ports:
      - '5000:5000'
    depends_on:
      - db
  db:
    image: mysql:latest
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: mbviajens
      MYSQL_ROOT_PASSWORD: fatec
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
